In [14]:
# esse método nos permite aplicar regularizações L1 e L2 na mesma função, nesse caso utilizaremos Lasso e Ridge respectivamente

In [15]:
# para isso definiremos valores para uma constante(C) que representará o peso das fuções L1 e L2, esse peso deve ser um valor 
# entre 0 e 1, o peso da função L1 será a própria constante, já o da L2 será 1 - constante, dado pela fórmula: 
# ERRO + C(L1) + (1-C)(L2)
# desse forma uma constante com valor 0.5 significa 50% de peso para cada, 1 significa 100% de peso para a L1, e por aí vai

In [16]:
from sklearn.linear_model import ElasticNet
import pandas as pd 
pd.set_option('display.max_columns',21)
dados = pd.read_csv('C:/Users/Cliente/IA/basesDeDados/kc_house_data.csv')
dados.head()
#importar a base de dados

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [17]:
from sklearn.model_selection import train_test_split
dados.drop('id',axis=1,inplace=True)
dados.drop('date',axis=1,inplace=True)
dados.drop('zipcode',axis=1,inplace=True)
dados.drop('lat',axis=1,inplace=True)
dados.drop('long',axis=1,inplace=True)

In [18]:
y = dados['price'] 
x = dados.drop('price',axis=1) 
x_treino, x_teste,y_treino,y_teste = train_test_split(x,y,test_size=0.30)

In [30]:
modelo = ElasticNet(l1_ratio = 0.9,tol = 0.001,max_iter = 5000) #l1 ratio é a constante que define os pesos
modelo.fit(x_treino,y_treino)
resultado = modelo.score(x_teste,y_teste)
print (resultado)

0.6513613208590013

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 393724884285397.0, tolerance: 2075889481792.0571
  model = cd_fast.enet_coordinate_descent(