In [2]:
# esse arquivo permite realizar novamente a comparação entre os modelos regressão, contudo dessa vez o resultado será mais
# preciso pois utilizaremos o crusamento de dados kfold para anular o erro gerado pela divisão aleatória de dados entre treino e
# teste

In [3]:
import pandas as pd

In [4]:
pd.set_option('display.max_columns',21)
dados = pd.read_csv('C:/Users/Cliente/IA/basesDeDados/kc_house_data.csv')
dados.head()
# utilizarei a maior e mais complexa base de dados que possuo para averiguar a eficácia do modelo

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [5]:
dados.drop('id',axis=1,inplace=True)
dados.drop('date',axis=1,inplace=True)
dados.drop('zipcode',axis=1,inplace=True)
dados.drop('lat',axis=1,inplace=True)
dados.drop('long',axis=1,inplace=True)
# excluir colunas irrelevantes e não numéricas

In [6]:
y = dados['price'] 
x = dados.drop('price',axis=1)

In [7]:
def modelos(x,y):
    from sklearn.linear_model import Lasso
    from sklearn.linear_model import Ridge
    from sklearn.linear_model import LinearRegression
    from sklearn.linear_model import ElasticNet
    from sklearn.model_selection import cross_val_score, KFold
    
    reg = LinearRegression()
    ridge = Ridge()
    lasso = Lasso()
    elastic = ElasticNet()
    
    kfold  = KFold(n_splits = 5)
    
    Rreg = cross_val_score(reg,x,y,cv = kfold)
    RFreg = max(Rreg)
    Rridge = cross_val_score(ridge,x,y,cv = kfold)
    RFridge = max(Rridge)
    Rlasso = cross_val_score(lasso,x,y,cv = kfold)
    RFlasso = max(Rlasso)
    Relastic = cross_val_score(elastic,x,y,cv = kfold)
    RFelastic = max(Relastic)
    
    print('Regressão linear:',RFreg,'Ridge:',RFridge,'Lasso:',RFlasso,'Elastic:',RFelastic)

In [8]:
modelos(x,y) # os resultado melhoraram em torno de 0.4% e 1.2%

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 361556959003298.75, tolerance: 225807564727.40997
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 363604775009838.6, tolerance: 230623895046.63632
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 375736810983811.56, tolerance: 240674810880.2502
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 375090871854239.25, tolerance: 236427969154.55582
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 363432183302817.0, tolerance: 231517800603.3212
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 458528778354741.94, tolerance: 225807564727.40997
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 470543565848813.75, tolerance: 230623895046.63632
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 489240909022716.44, tolerance: 240674810880.2502
  model = cd_fast.enet_coordinate_descent(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 485960951699413.6, tolerance: 236427969154.55582
  model = cd_fast.enet_coordinate_descent(

Regressão linear: 0.6581133189404946 Ridge: 0.6582877382158294 Lasso: 0.6581183043652834 Elastic: 0.6364929040240435

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 461219066172281.2, tolerance: 231517800603.3212
  model = cd_fast.enet_coordinate_descent(